### ISSUE TITLE
ODV minor tweaks meta-issue

### ISSUE THREAD

**Issue by markjd84** [IntegratedTransportPlanning/gcvt#157]
Happy to pick up any of these, but in case others have time: 

Approx ordered by priority, highest first

- [ ] Something to emphasise 'loading' if that's what's happening at first. 
  - [ ] Likewise, when loaded, do everything we can to display something on the map, even if we have to pick an IV/DV combo at random/alphabetically. Ultimately, schema could hold the 'initial view'.
- [x] Display project title/description somewhere
- [ ] Deploy with a nice domain name
- [ ] Check that Merlin<>Corridors setting up works on ports <1024 (can't see why it wouldn't, but we had teething problems last time) 
- [x] ITP-RHDHV new logo
- [ ] Background Mapbox style is too washed out - @dbrenigjones pointed out it makes it very difficult to see geog context

**Comment by bovine3dom** [comment]
https://github.com/IntegratedTransportPlanning/gcvt/blob/4aa8243e5f28aa4c3cf0c782e665559b2537120f/src/frontend/js/index.js#L439

Defaults are already supported in Corridors so I think 

>  Likewise, when loaded, do everything we can to display something on the map, even if we have to pick an IV/DV combo at random/alphabetically. Ultimately, schema could hold the 'initial view'.

is a Merlin issue :)

```js
// JSON because TOML is hard to write
{project: {defaults: {dependent_variable: "interesting_one_here", independent_variables: {year: 2020}, map_origin: {lat: 100, lon: 100, zoom: 10}}}
```

---

> Something to emphasise 'loading' if that's what's happening at first. 

Supported on Corridors backend: https://github.com/IntegratedTransportPlanning/gcvt/blob/4aa8243e5f28aa4c3cf0c782e665559b2537120f/src/backend/src/app-mux.jl#L24

Just needs something to be displayed on the Corridors frontend and, once https://github.com/IntegratedTransportPlanning/od-merlin/pull/14 is merged, something to display it on the Merlin frontend.

---

> Display project title/description somewhere

https://github.com/IntegratedTransportPlanning/gcvt/blob/4aa8243e5f28aa4c3cf0c782e665559b2537120f/src/frontend/js/index.js#L1105 - 90% done - just needs a few extra bits of metadata adding (and maybe window.title being set)

---

> New logo

https://github.com/IntegratedTransportPlanning/gcvt/blob/4aa8243e5f28aa4c3cf0c782e665559b2537120f/src/frontend/js/index.js#L995 I commented all this out assuming you wouldn't need it on an internal tool, but it could be added back easily.

---

> Check that Merlin<>Corridors setting up works on ports <1024 (can't see why it wouldn't, but we had teething problems last time)

You just need to change the ports that are set to `2017` here - https://github.com/IntegratedTransportPlanning/od-visualisation/blob/6095448340da53754bbe787d219f208e07d145db/Caddyfile#L1 - and probably start Caddy as root. You don't need to change any of the other ports since they're only used internally.


So perhaps there's less work left than you think? :)

**Comment by markjd84** [comment]
Ah brill, thanks, yes looks like lots of it is very close to being done, or is just a schema/config change.

Yeh the logo might still be useful. Probably helps our internal politics to show the new logo (since some of the users may come from our 4950 new staff members.... ;)

**Comment by markjd84** [comment]
Addendum: I can do the logo thing. And most of the other stuff for that matter - sorry I hadn't meant this to sound like a list of 'you guys need to fix all this' - more a list of finishing ideas for all of us.
