### ISSUE TITLE
GCVT 3.0 / 0.3 meta issue

### ISSUE THREAD

**Issue by bovine3dom** [IntegratedTransportPlanning/gcvt#81]
Wanted to keep track of our to-do list.

## Reinstating old functionality

- [x] Offsets
    - presumably need to shift lines by +/- something in direction of normal, look at how R version did it
- [x] Widths and colour by absolute values
    - [x] Colours by abs
    - [x] Widths of lines: should this only be by abs, or should it use current comparison settings?
- [x] Allow hiding links and zones
- [x] Legend
- [x] Info on hover and click
    - [x] Find out what info is desired
- [ ] Parsing and using of metadata
    - [x] Scenario description
    - [x] Variable descriptions (current "help?" works OK - perhaps just add more paragraphs to that)
    - [x] Colour schemes
        - [ ] Direction of abs. colour scheme independent of good / smaller
        - [ ] Bins are currently ignored but quantile based seems to work fine - decide whether we need them
        - [ ] Quantised colourschemes? I think our current interpolated ones are better
    - [ ] Defaults - e.g. change RdYlGn en masse; change default scenario etc.
        - [ ] Percentiles for colourbar
- [x] Click on a zone to show values to that zone and centroid lines if desired
    - [x] Find out what "values to that zone" is - I think we're currently
    - [x] What should UI for toggling centroids be? Perhaps in pop-up?
    - [x] Should pop-up / centroids be preserved by URL?
    - [x] I (Oliver) am not happy with how the centroids look. Don't really understand that they're for - flows between zones? Perhaps just colouring the zones would be more obvious. Makes quite a mess at the moment.
    - [x] multiselection
- [ ] General aesthetics/UX of UI
    - [ ] Sliders could do with a scale

## Essential new stuff

- [ ] Wordpress site
    - [x] Exists with OK theme
    - [x] Embed map as iframe
    - [ ] Automatic oEmbed
- [x] Query string to set map
    - [x] Selected zone not saved, not certain that this is desired
- [x] Short descriptions (i.e. human readable names)
- [x] Hide menu (done but ugly)
- [x] Palettes
- [x] Show % change when comparing between scenarios (done but beware open issue evident when comparing DoNothing with DoNothing)
- [ ] Proper domain names (NB: WordPress domain must be changed first before deployment)
- [ ] Country outlines
- [x] Fast loading
    - [x] Works OK (but slowly) on 2G (i.e. 5kB/s!) connection
    - [x] Deploy on any machine with Docker fairly easily. Must be set up in advance as will download about ten gigabytes; sensitive data needs manual transfer
        - Mapbox is always remote so perhaps not worth it
- [x] Time graphs - proof of concept on `charts` branch
- [x] Great circles (90% done but some bugs to chase down)

## Nice to haves

- [ ] Summary statistics
- [x] Demo presentation (done but needs updating once oEmbed is fixed)
- [ ] Aesthetics points overlay
- [x] Embed graphs separately from map
    - [x] oEmbed 
    - [ ] link copier from map
- [x] Centroid presentation improvements
    - Slight duplicate of above - need to find out what they're actually for
- [x] Advanced mode UX improvements
    - I think this is essentially done - we have little tickboxes that show/hide various things
- [x] Work around so that the still can still be used with no or limited internet
    - Duplicate of "Fast loading"? "no internet" mode not possible while we use Mapbox layers. Colin had a "no basemap" mode that could be used again. Perhaps we could generate our own low res basemap and use that.

## Stuff for ITP to deliver

- [ ] Deployment to greenconnectivity.net and ITP owned servers
- [ ] Mark to read/understand the code
    - [x] bikeshed -> master branch

## Oliver's wishlist

- [ ] Example data + metadata for others to use
- [ ] Data specification
- [ ] Data processing step moved into Docker so that it can be updated easily
    - [ ] Moved from R to Julia
